### ISSUE TITLE
Ephemeral: KNative configuration: Concurrency issue with multiple Computations in parallel

### ISSUE THREAD

**Issue by kindlich** [carbynestack/carbynestack#19]
Hey there,

the current KNativeServing for ephemeral-generic does not set `.spec.template.spec.containerConcurrency`.

Therefore, KNative's default values will apply, which allows up to 50 concurrent requests (soft limit, can even be more) to the serving with no hard limit on how many in-flight requests each scaled pod can receive.
Since the ephemeral-generic pods should not have perform more than one computation in parallel, I suggest setting that value to `1`.

Example:
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    #SNIP
  labels:
    #SNIP
  name: ephemeral-generic
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      creationTimestamp: null
    spec:
      containerConcurrency: 1 #Prevent more than one in-flight request to the pods in parallel
      containers:
      #SNIP
  traffic:
  - latestRevision: true
    percent: 100
```

BR,
kindlich
